version: 0.0
os: linux
files: 
  -source: /studysesh-rest
  destination: /home/ec2-user/StudySesh-Backend
hook:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2_user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2_user


    