version: 0.2
phases:
  pre_build:
    commands:
      - cd studysesh-rest
      - echo Installing dependencies with yarn
      - yarn
  build:
    commands:
      - yarn run build
artifacts:
  files:
    - '**/*'
  base-directory: base_dir
  name: build-artifact-name
  discard-paths: no